language: python

sudo: false

cache: packages

python:
  - "3.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --only-upgrade autoconf
  - sudo apt-get install --only-upgrade automake
  - sudo apt-get install --only-upgrade autotools-dev
  - sudo apt-get install autoconf-archive

install:
  - sudo apt-get install libboost-dev
  - sudo apt-get install libboost-python-dev
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov
  - pip install pytest-cov

script:
  - py.test --cov=./

after_success:
  - codecov

