package:
  name: boost
  version: "0.0.1"

source:
  git_rev: 0.0.1
  git_url: https://github.com/dirmeier/boost.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.11.0
    - scipy >=0.18.0
    - pytest >=2.9.2
    - nose ==1.3.7
    - sphinx >=1.4.5
    - scikit-learn >=0.17.0
  run:
    - python
    - numpy >=1.11.0
    - scipy >=0.18.0
    - pytest >=2.9.2
    - nose ==1.3.7
    - sphinx >=1.4.5
    - scikit-learn >=0.17.0

test:
  imports:
    - boost

about:
  home: https://github.com/dirmeier/boost
  license: GNU General Public License v3 (GPLv3)
  summary: 'An boost.python project example'
  license_family: GPL3

